title: "My Portfolio"
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme

# Navigation Links
nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /work/
  - title: "Contact"
    url: /contact/
